spring:

  application:
    name: projetotodo

  datasource:
    url: jdbc:postgresql://dpg-ct1b540gph6c73bh5r80-a.oregon-postgres.render.com:5432/projetotodo
    username: projetotodo_user
    password: 221bVyTl0LZJLHXzwZKQ9ZD6EVqmcnL6
    driver-class-name: org.postgresql.Driver
    initialize: true

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgres